# Generated by Django 3.0.3 on 2020-07-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название организации')),
                ('bin', models.BigIntegerField(unique=True, verbose_name='БИН')),
                ('oked', models.BigIntegerField(unique=True, verbose_name='ОКЭД')),
                ('okpo', models.BigIntegerField(unique=True, verbose_name='ОКПО')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юридический адрес')),
                ('owner', models.CharField(blank=True, max_length=150, null=True, verbose_name='Руководитель')),
                ('created', models.DateField(blank=True, null=True, verbose_name='Время открытия')),
            ],
            options={
                'verbose_name': 'Организация',
            },
        ),
    ]
